version: '3'

services:


 app:
   ports:
     - "80:80"
   build: ./docker/app
   container_name: application
   volumes:
     - ./src:/var/www/html/public_html

# ----------------------------------
# MySQL
# ----------------------------------
 db:
   # Docker HubからMySQL5.7の公式イメージをダウンロードしてくる指定
   image: mysql:5.7
   container_name: application_db

   # コンテナ内の環境変数を指定。環境変数を渡すとビルド時に設定してくれるDockerイメージがあるので、利用の際はDocker Hubのサイトで確認する
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: application_db
     MYSQL_USER: appuser
     MYSQL_PASSWORD: secret
     TZ: 'Asia/Tokyo'

   # 起動時のコマンド
   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306


# ----------------------------------
# phpMyAdmin
# ----------------------------------
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:5

  container_name: application_phpmyadmin

  links:
     - db

  # localhost:8080 で phpmyadmin の管理画面にアクセス
  ports:
     - 8080:80

  # セッション情報をボリュームに設定して永続化
  volumes:
     - ./docker/phpmyadmin/sessions:/sessions